# Twitter login credentials -- for account @Chase_Davis_

CONSUMER_KEY = 'OfFBQY83dBiacHqimEqF0DN87'
CONSUMER_SECRET = 'bXTxwsHgo179HoTYSc2y9CWXJTqffcC5NiHWrSc5NbPCaFtiNp'

ACCESS_TOKEN = '285913352-UHrszFYlJcyqYvxzaK21OGZkStAWDCEMDLBfSXNq'
ACCESS_SECRET = 'N1hkAPPmh48w6yptpDiZXb44eMuRtfrFedwSMXhSdewGG'

REDDIT_SECRET = '1H8m4N6xaPlkKFX5saDhQQAeZ8Q'
